# Generated by Django 4.2.7 on 2025-08-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_permission_role_userrole_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='Professional job title or position', max_length=100),
        ),
    ]
