# Generated by Django 4.2.7 on 2025-08-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='database_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
