# Generated by Django 4.2.7 on 2025-08-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tenant_database_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='academic_year_start',
            field=models.CharField(blank=True, default='September', help_text='Month when academic year starts', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='first_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='grade_system',
            field=models.CharField(blank=True, default='K-12', help_text='Grade system used', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='marketing_emails_consent',
            field=models.BooleanField(default=False, help_text='Consent to receive marketing emails'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='newsletter_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='school_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='school_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='school_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='school_state',
            field=models.CharField(blank=True, help_text='State/Province', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='school_type',
            field=models.CharField(blank=True, help_text='Type of educational institution', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='setup_wizard_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='staff_count_range',
            field=models.CharField(blank=True, help_text='Expected number of staff', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='student_count_range',
            field=models.CharField(blank=True, help_text='Expected number of students', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When free trial expires', null=True),
        ),
    ]
